/** Default CMS payload for leadership chronicle — aligned with original-web/about.html */

export const LEADERSHIP_CHRONICLE_DEFAULT_CONTENT = {
  eyebrow: "Leadership Chronicle",
  eyebrow_icon: "fa-scroll",
  title: "A Legacy of Faithful Service",
  subtitle:
    "Since 1959, faithful shepherds have guided Caritas Rwanda through decades of challenge, growth, and transformation — each era leaving a lasting mark on our mission.",
  anchor_id: "leadership",
  watermark_text: "SINCE 1959",
  groups: [
    {
      subgroup_label: "Chairpersons",
      subgroup_icon: "fa-crown",
      era_span: "1959 — Present",
      members: [
        {
          year: "1959",
          name: "Archbishop Perraudin",
          role: "Founding Chairperson",
          period: "1959 — 1972 · 13 yrs",
          duration: 13,
          photo_url: "/img/Chairperson/perraudin.jpg",
        },
        {
          year: "1972",
          name: "H.E. Mgr. Jean Baptiste Gahamanyi",
          role: "Chairperson",
          period: "1972 — 1997 · 25 yrs",
          duration: 25,
          photo_url: "/img/Chairperson/gahamanyi.png",
        },
        {
          year: "1997",
          name: "H.E. Mgr. Thaddée Ntihinyurwa",
          role: "Chairperson",
          period: "1997 — 2022 · 25 yrs",
          duration: 25,
          photo_url: "",
        },
        {
          year: "2022",
          name: "H.E. Mgr. Anaclet Mwumvaneza",
          role: "Chairperson — Nyundo Diocese",
          period: "2022 — Present",
          duration: 4,
          photo_url: "/img/Chairperson/anaclet.jpg",
          featured: true,
        },
      ],
    },
    {
      subgroup_label: "Secretary Generals",
      subgroup_icon: "fa-person-chalkboard",
      era_span: "1961 — Present",
      members: [
        {
          year: "1961",
          name: "Father Arthur Dejemeppe",
          role: "Secretary General",
          period: "1961 — 1972 · 11 yrs",
          duration: 11,
          photo_url: "/img/Secretary Generals/Arthur Dejemeppe.jpg",
        },
        {
          year: "1972",
          name: "Father Roger Pien",
          role: "Secretary General",
          period: "1972 — 1973 · 1 yr",
          duration: 1,
          photo_url: "/img/Secretary Generals/Roger Pien.jpg",
        },
        {
          year: "1973",
          name: "Father Cyriaque Munyansanga",
          role: "Secretary General",
          period: "1973 — 1977 · 4 yrs",
          duration: 4,
          photo_url: "/img/Secretary Generals/Cyriaque Munyansanga.png",
        },
        {
          year: "1977",
          name: "Father Carles Maria Giol",
          role: "Secretary General",
          period: "1977 — 1978 · 1 yr",
          duration: 1,
          photo_url: "/img/Secretary Generals/Carles Maria Giol.png",
        },
        {
          year: "1978",
          name: "Father Michel Descombes",
          role: "Secretary General",
          period: "1978 — 1995 · 17 yrs",
          duration: 17,
          photo_url: "/img/Secretary Generals/Descombers.jpg",
        },
        {
          year: "1995",
          name: "Father Callixte Twagirayezu",
          role: "Secretary General",
          period: "1995 — 1996 · 1 yr",
          duration: 1,
          photo_url: "/img/Secretary Generals/Callixte Twagirayezu.jpg",
        },
        {
          year: "1996",
          name: "Msgr. Oreste Incimatata",
          role: "Secretary General",
          period: "1996 — 2013 · 17 yrs",
          duration: 17,
          photo_url: "/img/Secretary Generals/Mgr. ORESTE INCIMATATA.jpg",
        },
        {
          year: "2013",
          name: "H.E. Mgr. Anaclet Mwumvaneza",
          role: "Secretary General",
          period: "2013 — 2016 · 3 yrs",
          duration: 3,
          photo_url: "/img/Secretary Generals/anaclet.jpg",
        },
        {
          year: "2016",
          name: "H.E. Mgr. JMV Twagirayezu",
          role: "Secretary General",
          period: "2016 — 2023 · 7 yrs",
          duration: 7,
          photo_url: "/img/Secretary Generals/JMV Twagirayezu.jpg",
        },
        {
          year: "2023",
          name: "Father Oscar Kagimbura",
          role: "Secretary General",
          period: "2023 — Present",
          duration: 3,
          photo_url: "/img/Secretary Generals/Oscar Kagimbura.png",
          featured: true,
        },
      ],
    },
  ],
};
